# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: productos.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'productos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fproductos.proto\x12\tproductos\"Z\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x0e\n\x06precio\x18\x04 \x01(\x02\x12\r\n\x05stock\x18\x05 \x01(\x05\"\x1d\n\x0fProductoRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\x07\n\x05\x45mpty2\x8b\x02\n\x10ProductosService\x12:\n\x0e\x43reateProducto\x12\x13.productos.Producto\x1a\x13.productos.Producto\x12?\n\x0cReadProducto\x12\x1a.productos.ProductoRequest\x1a\x13.productos.Producto\x12:\n\x0eUpdateProducto\x12\x13.productos.Producto\x1a\x13.productos.Producto\x12>\n\x0e\x44\x65leteProducto\x12\x1a.productos.ProductoRequest\x1a\x10.productos.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'productos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTO']._serialized_start=30
  _globals['_PRODUCTO']._serialized_end=120
  _globals['_PRODUCTOREQUEST']._serialized_start=122
  _globals['_PRODUCTOREQUEST']._serialized_end=151
  _globals['_EMPTY']._serialized_start=153
  _globals['_EMPTY']._serialized_end=160
  _globals['_PRODUCTOSSERVICE']._serialized_start=163
  _globals['_PRODUCTOSSERVICE']._serialized_end=430
# @@protoc_insertion_point(module_scope)
