# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import productos_pb2 as productos__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in productos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProductosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProducto = channel.unary_unary(
                '/productos.ProductosService/CreateProducto',
                request_serializer=productos__pb2.Producto.SerializeToString,
                response_deserializer=productos__pb2.Producto.FromString,
                _registered_method=True)
        self.ReadProducto = channel.unary_unary(
                '/productos.ProductosService/ReadProducto',
                request_serializer=productos__pb2.ProductoRequest.SerializeToString,
                response_deserializer=productos__pb2.Producto.FromString,
                _registered_method=True)
        self.UpdateProducto = channel.unary_unary(
                '/productos.ProductosService/UpdateProducto',
                request_serializer=productos__pb2.Producto.SerializeToString,
                response_deserializer=productos__pb2.Producto.FromString,
                _registered_method=True)
        self.DeleteProducto = channel.unary_unary(
                '/productos.ProductosService/DeleteProducto',
                request_serializer=productos__pb2.ProductoRequest.SerializeToString,
                response_deserializer=productos__pb2.Empty.FromString,
                _registered_method=True)


class ProductosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProductosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProducto,
                    request_deserializer=productos__pb2.Producto.FromString,
                    response_serializer=productos__pb2.Producto.SerializeToString,
            ),
            'ReadProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadProducto,
                    request_deserializer=productos__pb2.ProductoRequest.FromString,
                    response_serializer=productos__pb2.Producto.SerializeToString,
            ),
            'UpdateProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProducto,
                    request_deserializer=productos__pb2.Producto.FromString,
                    response_serializer=productos__pb2.Producto.SerializeToString,
            ),
            'DeleteProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProducto,
                    request_deserializer=productos__pb2.ProductoRequest.FromString,
                    response_serializer=productos__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'productos.ProductosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('productos.ProductosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProductosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos.ProductosService/CreateProducto',
            productos__pb2.Producto.SerializeToString,
            productos__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos.ProductosService/ReadProducto',
            productos__pb2.ProductoRequest.SerializeToString,
            productos__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos.ProductosService/UpdateProducto',
            productos__pb2.Producto.SerializeToString,
            productos__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/productos.ProductosService/DeleteProducto',
            productos__pb2.ProductoRequest.SerializeToString,
            productos__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
